name: Nintendo Switch

on:
  workflow_dispatch:
  push:
    branches: [ switch-port-2.2.13 ]
  pull_request:
    branches: [ switch-port-2.2.13 ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - name: Install 7z/zip
      run: |
        apt-get update
        apt-get install -y zip p7zip-full
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: make clean
      run: make PLATFORM=Switch clean
    - name: make 
      run: make PLATFORM=Switch
    - name: Upload NRO
      uses: actions/upload-artifact@v2
      with:
        name: nro
        path: bin/Switch/srb2switch22.nro
