name: Nintendo Switch

on:
  push:
    branches: [ switch-port ]
  pull_request:
    branches: [ switch-port ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: devkitpro/devkita64:20200730
    steps:
    - name: Install 7z/zip
      run: |
        apt-get update
        apt-get install -y zip p7zip-full
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Download assets
      run: sh ./downloadassets.sh
    - name: make clean
      run: make PLATFORM=Switch clean
    - name: make 
      run: make PLATFORM=Switch
    - name: Upload NRO
      uses: actions/upload-artifact@v2
      with:
        name: nro
        path: bin/Switch/srb2switch22.nro